// DE10_Pro_QSYS_altera_mm_interconnect_191_uoukggi.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 19.2 57

`timescale 1 ps / 1 ps
module DE10_Pro_QSYS_altera_mm_interconnect_191_uoukggi (
		input  wire [2:0]  Pebbles_0_avalon_master_address,                                      //                                        Pebbles_0_avalon_master.address
		output wire        Pebbles_0_avalon_master_waitrequest,                                  //                                                               .waitrequest
		input  wire        Pebbles_0_avalon_master_read,                                         //                                                               .read
		output wire [31:0] Pebbles_0_avalon_master_readdata,                                     //                                                               .readdata
		input  wire        Pebbles_0_avalon_master_write,                                        //                                                               .write
		input  wire [31:0] Pebbles_0_avalon_master_writedata,                                    //                                                               .writedata
		output wire [0:0]  jtag_uart_1_avalon_jtag_slave_address,                                //                                  jtag_uart_1_avalon_jtag_slave.address
		output wire        jtag_uart_1_avalon_jtag_slave_write,                                  //                                                               .write
		output wire        jtag_uart_1_avalon_jtag_slave_read,                                   //                                                               .read
		input  wire [31:0] jtag_uart_1_avalon_jtag_slave_readdata,                               //                                                               .readdata
		output wire [31:0] jtag_uart_1_avalon_jtag_slave_writedata,                              //                                                               .writedata
		input  wire        jtag_uart_1_avalon_jtag_slave_waitrequest,                            //                                                               .waitrequest
		output wire        jtag_uart_1_avalon_jtag_slave_chipselect,                             //                                                               .chipselect
		input  wire        Pebbles_0_avalon_master_translator_reset_reset_bridge_in_reset_reset, // Pebbles_0_avalon_master_translator_reset_reset_bridge_in_reset.reset
		input  wire        iopll_0_outclk2_clk                                                   //                                                iopll_0_outclk2.clk
	);

	wire         pebbles_0_avalon_master_translator_avalon_universal_master_0_waitrequest;   // jtag_uart_1_avalon_jtag_slave_translator:uav_waitrequest -> Pebbles_0_avalon_master_translator:uav_waitrequest
	wire  [31:0] pebbles_0_avalon_master_translator_avalon_universal_master_0_readdata;      // jtag_uart_1_avalon_jtag_slave_translator:uav_readdata -> Pebbles_0_avalon_master_translator:uav_readdata
	wire         pebbles_0_avalon_master_translator_avalon_universal_master_0_debugaccess;   // Pebbles_0_avalon_master_translator:uav_debugaccess -> jtag_uart_1_avalon_jtag_slave_translator:uav_debugaccess
	wire   [2:0] pebbles_0_avalon_master_translator_avalon_universal_master_0_address;       // Pebbles_0_avalon_master_translator:uav_address -> jtag_uart_1_avalon_jtag_slave_translator:uav_address
	wire         pebbles_0_avalon_master_translator_avalon_universal_master_0_read;          // Pebbles_0_avalon_master_translator:uav_read -> jtag_uart_1_avalon_jtag_slave_translator:uav_read
	wire   [3:0] pebbles_0_avalon_master_translator_avalon_universal_master_0_byteenable;    // Pebbles_0_avalon_master_translator:uav_byteenable -> jtag_uart_1_avalon_jtag_slave_translator:uav_byteenable
	wire         pebbles_0_avalon_master_translator_avalon_universal_master_0_readdatavalid; // jtag_uart_1_avalon_jtag_slave_translator:uav_readdatavalid -> Pebbles_0_avalon_master_translator:uav_readdatavalid
	wire         pebbles_0_avalon_master_translator_avalon_universal_master_0_lock;          // Pebbles_0_avalon_master_translator:uav_lock -> jtag_uart_1_avalon_jtag_slave_translator:uav_lock
	wire         pebbles_0_avalon_master_translator_avalon_universal_master_0_write;         // Pebbles_0_avalon_master_translator:uav_write -> jtag_uart_1_avalon_jtag_slave_translator:uav_write
	wire  [31:0] pebbles_0_avalon_master_translator_avalon_universal_master_0_writedata;     // Pebbles_0_avalon_master_translator:uav_writedata -> jtag_uart_1_avalon_jtag_slave_translator:uav_writedata
	wire   [2:0] pebbles_0_avalon_master_translator_avalon_universal_master_0_burstcount;    // Pebbles_0_avalon_master_translator:uav_burstcount -> jtag_uart_1_avalon_jtag_slave_translator:uav_burstcount

	DE10_Pro_QSYS_altera_merlin_master_translator_191_g7h47bq #(
		.AV_ADDRESS_W                (3),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (3),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0),
		.SYNC_RESET                  (1),
		.WAITREQUEST_ALLOWANCE       (0)
	) pebbles_0_avalon_master_translator (
		.clk                    (iopll_0_outclk2_clk),                                                        //   input,   width = 1,                       clk.clk
		.reset                  (Pebbles_0_avalon_master_translator_reset_reset_bridge_in_reset_reset),       //   input,   width = 1,                     reset.reset
		.uav_address            (pebbles_0_avalon_master_translator_avalon_universal_master_0_address),       //  output,   width = 3, avalon_universal_master_0.address
		.uav_burstcount         (pebbles_0_avalon_master_translator_avalon_universal_master_0_burstcount),    //  output,   width = 3,                          .burstcount
		.uav_read               (pebbles_0_avalon_master_translator_avalon_universal_master_0_read),          //  output,   width = 1,                          .read
		.uav_write              (pebbles_0_avalon_master_translator_avalon_universal_master_0_write),         //  output,   width = 1,                          .write
		.uav_waitrequest        (pebbles_0_avalon_master_translator_avalon_universal_master_0_waitrequest),   //   input,   width = 1,                          .waitrequest
		.uav_readdatavalid      (pebbles_0_avalon_master_translator_avalon_universal_master_0_readdatavalid), //   input,   width = 1,                          .readdatavalid
		.uav_byteenable         (pebbles_0_avalon_master_translator_avalon_universal_master_0_byteenable),    //  output,   width = 4,                          .byteenable
		.uav_readdata           (pebbles_0_avalon_master_translator_avalon_universal_master_0_readdata),      //   input,  width = 32,                          .readdata
		.uav_writedata          (pebbles_0_avalon_master_translator_avalon_universal_master_0_writedata),     //  output,  width = 32,                          .writedata
		.uav_lock               (pebbles_0_avalon_master_translator_avalon_universal_master_0_lock),          //  output,   width = 1,                          .lock
		.uav_debugaccess        (pebbles_0_avalon_master_translator_avalon_universal_master_0_debugaccess),   //  output,   width = 1,                          .debugaccess
		.av_address             (Pebbles_0_avalon_master_address),                                            //   input,   width = 3,      avalon_anti_master_0.address
		.av_waitrequest         (Pebbles_0_avalon_master_waitrequest),                                        //  output,   width = 1,                          .waitrequest
		.av_read                (Pebbles_0_avalon_master_read),                                               //   input,   width = 1,                          .read
		.av_readdata            (Pebbles_0_avalon_master_readdata),                                           //  output,  width = 32,                          .readdata
		.av_write               (Pebbles_0_avalon_master_write),                                              //   input,   width = 1,                          .write
		.av_writedata           (Pebbles_0_avalon_master_writedata),                                          //   input,  width = 32,                          .writedata
		.av_burstcount          (1'b1),                                                                       // (terminated),                                        
		.av_byteenable          (4'b1111),                                                                    // (terminated),                                        
		.av_beginbursttransfer  (1'b0),                                                                       // (terminated),                                        
		.av_begintransfer       (1'b0),                                                                       // (terminated),                                        
		.av_chipselect          (1'b0),                                                                       // (terminated),                                        
		.av_readdatavalid       (),                                                                           // (terminated),                                        
		.av_lock                (1'b0),                                                                       // (terminated),                                        
		.av_debugaccess         (1'b0),                                                                       // (terminated),                                        
		.uav_clken              (),                                                                           // (terminated),                                        
		.av_clken               (1'b1),                                                                       // (terminated),                                        
		.uav_response           (2'b00),                                                                      // (terminated),                                        
		.av_response            (),                                                                           // (terminated),                                        
		.uav_writeresponsevalid (1'b0),                                                                       // (terminated),                                        
		.av_writeresponsevalid  ()                                                                            // (terminated),                                        
	);

	DE10_Pro_QSYS_altera_merlin_slave_translator_191_x56fcki #(
		.AV_ADDRESS_W                   (1),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (1),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (3),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0),
		.WAITREQUEST_ALLOWANCE          (0),
		.SYNC_RESET                     (1)
	) jtag_uart_1_avalon_jtag_slave_translator (
		.clk                    (iopll_0_outclk2_clk),                                                        //   input,   width = 1,                      clk.clk
		.reset                  (Pebbles_0_avalon_master_translator_reset_reset_bridge_in_reset_reset),       //   input,   width = 1,                    reset.reset
		.uav_address            (pebbles_0_avalon_master_translator_avalon_universal_master_0_address),       //   input,   width = 3, avalon_universal_slave_0.address
		.uav_burstcount         (pebbles_0_avalon_master_translator_avalon_universal_master_0_burstcount),    //   input,   width = 3,                         .burstcount
		.uav_read               (pebbles_0_avalon_master_translator_avalon_universal_master_0_read),          //   input,   width = 1,                         .read
		.uav_write              (pebbles_0_avalon_master_translator_avalon_universal_master_0_write),         //   input,   width = 1,                         .write
		.uav_waitrequest        (pebbles_0_avalon_master_translator_avalon_universal_master_0_waitrequest),   //  output,   width = 1,                         .waitrequest
		.uav_readdatavalid      (pebbles_0_avalon_master_translator_avalon_universal_master_0_readdatavalid), //  output,   width = 1,                         .readdatavalid
		.uav_byteenable         (pebbles_0_avalon_master_translator_avalon_universal_master_0_byteenable),    //   input,   width = 4,                         .byteenable
		.uav_readdata           (pebbles_0_avalon_master_translator_avalon_universal_master_0_readdata),      //  output,  width = 32,                         .readdata
		.uav_writedata          (pebbles_0_avalon_master_translator_avalon_universal_master_0_writedata),     //   input,  width = 32,                         .writedata
		.uav_lock               (pebbles_0_avalon_master_translator_avalon_universal_master_0_lock),          //   input,   width = 1,                         .lock
		.uav_debugaccess        (pebbles_0_avalon_master_translator_avalon_universal_master_0_debugaccess),   //   input,   width = 1,                         .debugaccess
		.av_address             (jtag_uart_1_avalon_jtag_slave_address),                                      //  output,   width = 1,      avalon_anti_slave_0.address
		.av_write               (jtag_uart_1_avalon_jtag_slave_write),                                        //  output,   width = 1,                         .write
		.av_read                (jtag_uart_1_avalon_jtag_slave_read),                                         //  output,   width = 1,                         .read
		.av_readdata            (jtag_uart_1_avalon_jtag_slave_readdata),                                     //   input,  width = 32,                         .readdata
		.av_writedata           (jtag_uart_1_avalon_jtag_slave_writedata),                                    //  output,  width = 32,                         .writedata
		.av_waitrequest         (jtag_uart_1_avalon_jtag_slave_waitrequest),                                  //   input,   width = 1,                         .waitrequest
		.av_chipselect          (jtag_uart_1_avalon_jtag_slave_chipselect),                                   //  output,   width = 1,                         .chipselect
		.av_begintransfer       (),                                                                           // (terminated),                                       
		.av_beginbursttransfer  (),                                                                           // (terminated),                                       
		.av_burstcount          (),                                                                           // (terminated),                                       
		.av_byteenable          (),                                                                           // (terminated),                                       
		.av_readdatavalid       (1'b0),                                                                       // (terminated),                                       
		.av_writebyteenable     (),                                                                           // (terminated),                                       
		.av_lock                (),                                                                           // (terminated),                                       
		.av_clken               (),                                                                           // (terminated),                                       
		.uav_clken              (1'b0),                                                                       // (terminated),                                       
		.av_debugaccess         (),                                                                           // (terminated),                                       
		.av_outputenable        (),                                                                           // (terminated),                                       
		.uav_response           (),                                                                           // (terminated),                                       
		.av_response            (2'b00),                                                                      // (terminated),                                       
		.uav_writeresponsevalid (),                                                                           // (terminated),                                       
		.av_writeresponsevalid  (1'b0)                                                                        // (terminated),                                       
	);

endmodule
