# TCL File Generated by Component Editor 19.2
# Fri Nov 06 21:48:04 UTC 2020
# DO NOT MODIFY


# 
# PowerReader "PowerReader" v1.0
#  2020.11.06.21:48:04
# 
# 

# 
# request TCL package from ACDS 19.4
# 
package require -exact qsys 19.4


# 
# module PowerReader
# 
set_module_property DESCRIPTION ""
set_module_property NAME PowerReader
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME PowerReader
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkPowerReader
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mkPowerReader.v VERILOG PATH ../temperature/mkPowerReader.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock CLK clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""
set_interface_property reset_sink IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset_sink RST_N reset_n Input 1


# 
# connection point power_i2c
# 
add_interface power_i2c conduit end
set_interface_property power_i2c associatedClock clock
set_interface_property power_i2c associatedReset reset_sink
set_interface_property power_i2c ENABLED true
set_interface_property power_i2c EXPORT_OF ""
set_interface_property power_i2c PORT_NAME_MAP ""
set_interface_property power_i2c CMSIS_SVD_VARIABLES ""
set_interface_property power_i2c SVD_ADDRESS_GROUP ""
set_interface_property power_i2c IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port power_i2c POWER_I2C_SDA export_sda Bidir 1
add_interface_port power_i2c POWER_I2C_SCL export_scl Bidir 1


# 
# connection point power_min
# 
add_interface power_min conduit end
set_interface_property power_min associatedClock clock
set_interface_property power_min associatedReset reset_sink
set_interface_property power_min ENABLED true
set_interface_property power_min EXPORT_OF ""
set_interface_property power_min PORT_NAME_MAP ""
set_interface_property power_min CMSIS_SVD_VARIABLES ""
set_interface_property power_min SVD_ADDRESS_GROUP ""
set_interface_property power_min IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port power_min get_power_min power_min Output 24


# 
# connection point power_max
# 
add_interface power_max conduit end
set_interface_property power_max associatedClock clock
set_interface_property power_max associatedReset reset_sink
set_interface_property power_max ENABLED true
set_interface_property power_max EXPORT_OF ""
set_interface_property power_max PORT_NAME_MAP ""
set_interface_property power_max CMSIS_SVD_VARIABLES ""
set_interface_property power_max SVD_ADDRESS_GROUP ""
set_interface_property power_max IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port power_max get_power_max power_max Output 24

