# TCL File Generated by Component Editor 19.2
# Thu Oct 29 15:34:39 UTC 2020
# DO NOT MODIFY


# 
# TempReader "TempReader" v1.0
#  2020.10.29.15:34:39
# 
# 

# 
# request TCL package from ACDS 19.4
# 
package require -exact qsys 19.4


# 
# module TempReader
# 
set_module_property DESCRIPTION ""
set_module_property NAME TempReader
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME TempReader
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkTempReader
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mkTempReader.v VERILOG PATH mkTempReader.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock CLK clk Input 1


# 
# connection point reset_in
# 
add_interface reset_in reset end
set_interface_property reset_in associatedClock clock
set_interface_property reset_in synchronousEdges DEASSERT
set_interface_property reset_in ENABLED true
set_interface_property reset_in EXPORT_OF ""
set_interface_property reset_in PORT_NAME_MAP ""
set_interface_property reset_in CMSIS_SVD_VARIABLES ""
set_interface_property reset_in SVD_ADDRESS_GROUP ""
set_interface_property reset_in IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset_in RST_N reset_n Input 1


# 
# connection point i2c_signals
# 
add_interface i2c_signals conduit end
set_interface_property i2c_signals associatedClock clock
set_interface_property i2c_signals associatedReset reset_in
set_interface_property i2c_signals ENABLED true
set_interface_property i2c_signals EXPORT_OF ""
set_interface_property i2c_signals PORT_NAME_MAP ""
set_interface_property i2c_signals CMSIS_SVD_VARIABLES ""
set_interface_property i2c_signals SVD_ADDRESS_GROUP ""
set_interface_property i2c_signals IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port i2c_signals TEMP_I2C_SCL scl Bidir 1
add_interface_port i2c_signals TEMP_I2C_SDA sda Bidir 1


# 
# connection point temp_out
# 
add_interface temp_out conduit end
set_interface_property temp_out associatedClock clock
set_interface_property temp_out associatedReset reset_in
set_interface_property temp_out ENABLED true
set_interface_property temp_out EXPORT_OF ""
set_interface_property temp_out PORT_NAME_MAP ""
set_interface_property temp_out CMSIS_SVD_VARIABLES ""
set_interface_property temp_out SVD_ADDRESS_GROUP ""
set_interface_property temp_out IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port temp_out get_temp export Output 8

